"""add min_years_required to jobs

Revision ID: 4475eb486d90
Revises: 781f7635d6a3
Create Date: 2026-07-10 14:26:43.698640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4475eb486d90'
down_revision: Union[str, Sequence[str], None] = '781f7635d6a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('min_years_required', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'min_years_required')
    # ### end Alembic commands ###
